### PR TITLE
 Only write heading in blue if stdout is terminal

### PR DESCRIPTION
**Pull request by lassik**
Adds a new method `writeOutHeading` to the `BaseCommand` class.

Fixes some of the failing unit tests in #95.

### CODE REVIEW

**Comment by lassik** [comment]
Verified that this works locally on Mac. By comparing the output of `unibeautify support -l` (shows colors) and `unibeautify support -l | cat` (doesn't show color) in a terminal window.

**Comment by lassik** [comment]
Travis failed on Linux due to some Node/NPM update taking ages. Please retry it.

**Comment by stevenzeck** [comment]
@lassik I removed the Travis CI and Unibeautify - Branch status check requirements, it doesn't work unless you have your fork setup to run Travis (I think).

**Comment by lassik** [comment]
Thanks for merging. In the future, we ought to rebase each PR to the latest master before merging it. The Git history (`git log --graph`) gets quite convoluted otherwise :)

**Pull request merged**
